#!/bin/bash
CONTEXT="$1"
if [ -z "$CONTEXT" ]; then echo "Usage: $0 <context>"; exit 1; fi
if echo "$CONTEXT" | grep -qi "happy\|excited\|joy"; then echo "😊 🙌 🎉"
elif echo "$CONTEXT" | grep -qi "thinking\|consider"; then echo "🤔 💭 🧠"
elif echo "$CONTEXT" | grep -qi "idea\|insight"; then echo "💡 ✨ 🎯"
elif echo "$CONTEXT" | grep -qi "problem\|issue\|bug"; then echo "🔧 🐛 🤔"
elif echo "$CONTEXT" | grep -qi "done\|complete"; then echo "✅ 🎉 👍"
elif echo "$CONTEXT" | grep -qi "thank\|grateful"; then echo "🙏 ❤️ 💚"
elif echo "$CONTEXT" | grep -qi "love\|care"; then echo "❤️ 💚 🫶"
elif echo "$CONTEXT" | grep -qi "work\|professional"; then echo "💼 🎯 📊"
elif echo "$CONTEXT" | grep -qi "research\|search"; then echo "🔍 🧭 📚"
elif echo "$CONTEXT" | grep -qi "start\|begin\|launch"; then echo "🚀 ▶️ 🌟"
elif echo "$CONTEXT" | grep -qi "stop\|end\|finish"; then echo "🛑 ⏹️ ✅"
elif echo "$CONTEXT" | grep -qi "question\|ask"; then echo "❓ 🤔 💭"
elif echo "$CONTEXT" | grep -qi "answer\|explain"; then echo "💡 ✅ 📝"
elif echo "$CONTEXT" | grep -qi "celebrate\|win\|success"; then echo "🎉 🏆 🙌"
elif echo "$CONTEXT" | grep -qi "code\|build\|tech"; then echo "💻 🔧 🛠️"
elif echo "$CONTEXT" | grep -qi "web\|online"; then echo "🌐 🔍 📡"
elif echo "$CONTEXT" | grep -qi "data\|stats"; then echo "📊 📈 💾"
else echo "💡 🤔 ✅"; fi
